# Generated by Django 4.2.7 on 2026-03-05 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='domain',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
